// Stages packages/sdk/ — the source a mod is written against — from this repo's own SDK. Every
// module the two entrypoints reach is copied verbatim, with only the "@/" import aliases rewritten
// into relative paths, so an author's editor resolves the real code and its comments.
//
//   node tools/pack-sdk.js [--check]
//
// --check only compares what is staged against what these sources imply, so a stale copy fails CI.

import {existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync} from "node:fs";
import {dirname, join, relative, resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {parseArgs} from "node:util";
import {parse} from "acorn";
import {gitBuildInfo} from "../vite.build-defines.js";
import {SDK_VERSION} from "../src/common/ModManifest.js";
import {syncPackageVersion} from "./packageVersion.js";
import {GAME_VERSION} from "../src/common/constants.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC_DIR = join(ROOT, "src");
const PACKAGE_DIR = join(ROOT, "packages/sdk");
const SOURCE_DIR = join(PACKAGE_DIR, "dist");
const PACKED_FILE = join(PACKAGE_DIR, "packed.json");

const ENTRIES = ["sdk/common.js", "sdk/client.js"];

// Enough stale names to recognise what happened, without listing a whole re-pack.
const STALE_FILES_SHOWN = 5;

// The engine reads the game version out of the repo's package.json, which has no place in a
// published package; the staged copy imports this generated module instead.
const VERSION_MODULE = "gameVersion.js";
const VERSION_SOURCE = "// Generated by tools/pack-sdk.js from this repo's package.json.\n"
    + `export default {version: ${JSON.stringify(GAME_VERSION)}};\n`;

/**
 * Every import/export specifier in a module: where the specifier sits, and where its whole
 * declaration ends (an import attribute like `with {type: "json"}` sits in between).
 * @param {string} source
 * @returns {Array<{value: string, start: number, end: number, declarationEnd: number}>}
 */
function specifiersIn(source) {
    const found = [];
    const ast = parse(source, {ecmaVersion: "latest", sourceType: "module"});
    for (const node of ast.body) {
        if (node.source !== undefined && node.source !== null) {
            found.push({
                value: node.source.value,
                start: node.source.start,
                end: node.source.end,
                declarationEnd: node.end,
            });
        }
    }
    return found;
}

/**
 * The file an import points at, or null when it names a package (pixi.js, protobufjs) that the
 * staged copy leaves alone.
 * @param {string} specifier
 * @param {string} fromFile
 * @returns {string|null}
 */
function targetOf(specifier, fromFile) {
    if (specifier.startsWith("@/")) {
        return join(SRC_DIR, specifier.slice(2));
    }
    if (specifier.startsWith(".")) {
        return resolve(dirname(fromFile), specifier);
    }
    return null;
}

/**
 * @param {string} fromFile
 * @param {string} toFile
 * @returns {string} a relative specifier, "./"-prefixed the way an import needs
 */
function relativeSpecifier(fromFile, toFile) {
    const path = relative(dirname(fromFile), toFile).replaceAll("\\", "/");
    if (path.startsWith(".")) {
        return path;
    }
    return `./${path}`;
}

/**
 * Copies a module and everything it reaches, rewriting only the specifiers that would not resolve
 * outside this repo.
 * @param {string} file
 * @param {Map<string, string>} staged file -> rewritten source, filled as it goes
 * @param {Set<string>} packages package imports seen, filled as it goes
 * @returns {void}
 */
function stage(file, staged, packages) {
    if (staged.has(file)) {
        return;
    }
    const source = readFileSync(file, "utf8");
    staged.set(file, source);
    const edits = [];
    const reached = [];
    for (const specifier of specifiersIn(source)) {
        // The one import that cannot come along: the repo's package.json. Its JSON import
        // attribute goes with it, so the rewrite covers the rest of the statement.
        if (specifier.value.endsWith("package.json")) {
            const target = join(SRC_DIR, VERSION_MODULE);
            edits.push({
                start: specifier.start,
                end: specifier.declarationEnd,
                text: relativeSpecifier(file, target),
                terminate: true,
            });
            continue;
        }
        const target = targetOf(specifier.value, file);
        if (target === null) {
            packages.add(specifier.value);
            continue;
        }
        reached.push(target);
        if (specifier.value.startsWith("@/")) {
            edits.push({...specifier, text: relativeSpecifier(file, target)});
        }
    }
    let rewritten = source;
    for (const edit of edits.reverse()) {
        let text = JSON.stringify(edit.text);
        if (edit.terminate === true) {
            text = `${text};`;
        }
        rewritten = `${rewritten.slice(0, edit.start)}${text}${rewritten.slice(edit.end)}`;
    }
    staged.set(file, rewritten);
    for (const target of reached) {
        stage(target, staged, packages);
    }
}

/**
 * The dist/ contents this repo's sources imply.
 * @returns {{files: Map<string, string>, packages: string[]}} path under dist/ -> source
 */
function assemble() {
    const staged = new Map();
    const packages = new Set();
    for (const entry of ENTRIES) {
        stage(join(SRC_DIR, entry), staged, packages);
    }
    const files = new Map();
    for (const [file, source] of staged) {
        files.set(relative(SRC_DIR, file), source);
    }
    files.set(VERSION_MODULE, VERSION_SOURCE);
    return {files, packages: [...packages].sort()};
}

/**
 * @returns {{modules: number, packages: string[]}}
 */
function pack() {
    const {files, packages} = assemble();
    rmSync(SOURCE_DIR, {recursive: true, force: true});
    for (const [name, source] of files) {
        const path = join(SOURCE_DIR, name);
        mkdirSync(dirname(path), {recursive: true});
        writeFileSync(path, source);
    }
    return {modules: files.size, packages};
}

/**
 * @returns {string[]} the file names under dist/, in no particular order
 */
function stagedFiles() {
    if (!existsSync(SOURCE_DIR)) {
        return [];
    }
    return readdirSync(SOURCE_DIR, {recursive: true, withFileTypes: true})
        .filter(entry => entry.isFile())
        .map(entry => relative(SOURCE_DIR, join(entry.parentPath, entry.name)));
}

/**
 * What is stale about the staged copy. The sources are copied verbatim, so this compares content
 * rather than trusting a commit stamp: an uncommitted edit to the SDK is exactly the stale copy
 * worth catching.
 * @returns {string[]} empty when it is current
 */
function staleReasons() {
    if (!existsSync(PACKED_FILE)) {
        return ["nothing is staged"];
    }
    const packed = JSON.parse(readFileSync(PACKED_FILE, "utf8"));
    const reasons = [];
    if (packed.sdkVersion !== SDK_VERSION) {
        reasons.push(`built for SDK ${packed.sdkVersion}, this tree is ${SDK_VERSION}`);
    }
    const {files} = assemble();
    const changed = [];
    for (const [name, source] of files) {
        const path = join(SOURCE_DIR, name);
        if (!existsSync(path) || readFileSync(path, "utf8") !== source) {
            changed.push(name);
        }
    }
    if (changed.length > 0) {
        reasons.push(`${changed.length} file(s) differ: ${changed.slice(0, STALE_FILES_SHOWN).join(", ")}`);
    }
    const extra = stagedFiles().filter(name => !files.has(name));
    if (extra.length > 0) {
        reasons.push(`${extra.length} file(s) no longer belong: ${extra.slice(0, STALE_FILES_SHOWN).join(", ")}`);
    }
    return reasons;
}

const {values: args} = parseArgs({options: {"check": {type: "boolean", default: false}}});
if (args.check) {
    const reasons = staleReasons();
    if (reasons.length > 0) {
        console.error(`packages/sdk is stale: ${reasons.join("; ")}`);
        console.error("run `npm run pack:sdk`");
        process.exitCode = 1;
    } else {
        console.log("packages/sdk is current");
    }
} else {
    syncPackageVersion(PACKAGE_DIR);
    const {modules, packages} = pack();
    writeFileSync(PACKED_FILE, `${JSON.stringify({commit: gitBuildInfo().commit, sdkVersion: SDK_VERSION}, null, 4)}\n`);
    console.log(`packages/sdk: ${modules} modules, SDK version ${SDK_VERSION}`);
    console.log(`  imports: ${packages.join(", ")}`);
}
